// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_9xUtHPmS2-qvA2qsv3iqNiob_Bm8Trk',
    appId: '1:240047024105:web:1113564ef9024222eecd78',
    messagingSenderId: '240047024105',
    projectId: 'medin-c092a',
    authDomain: 'medin-c092a.firebaseapp.com',
    databaseURL: 'https://medin-c092a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medin-c092a.appspot.com',
    measurementId: 'G-F8M0WV920N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDiUkoqHuU9MSuVNpPYJFlOFO841CocA',
    appId: '1:240047024105:android:6b7b6f49c689249feecd78',
    messagingSenderId: '240047024105',
    projectId: 'medin-c092a',
    databaseURL: 'https://medin-c092a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medin-c092a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RD2fRfuSBRe9dRcHtzm5mCVKDhmivbY',
    appId: '1:240047024105:ios:ab3ce7598583901aeecd78',
    messagingSenderId: '240047024105',
    projectId: 'medin-c092a',
    databaseURL: 'https://medin-c092a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medin-c092a.appspot.com',
    iosClientId: '240047024105-lp4ik5g5vmchiqi50p58dv9tptsfftm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.medin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_RD2fRfuSBRe9dRcHtzm5mCVKDhmivbY',
    appId: '1:240047024105:ios:5a1ed108ca5818d1eecd78',
    messagingSenderId: '240047024105',
    projectId: 'medin-c092a',
    databaseURL: 'https://medin-c092a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medin-c092a.appspot.com',
    iosClientId: '240047024105-mko8vngf934hclun5qf76vcoahr1jk0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.medin.RunnerTests',
  );
}
